import {StyleSheet} from 'react-native';
import {Colors} from '../../../assets/Colors';
import Fonts from '../../../assets/fonts';
export const Styles = StyleSheet.create({
  headercontainer: {
    paddingHorizontal: '5%',
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F6F5',
    elevation: 5,
    marginBottom: 4,
    width: '100%',
  },
  leftarrowbox: {width: '10%'},
  headerinputbox: {
    width: '85%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    borderRadius: 60,
    marginLeft: 10,
  },
  txtinput: {
    width: '90%',
    fontSize: 14,
    fontFamily: Fonts.AssistantRegular,
  },
  righticonbox: {width: '10%', alignItems: 'center'},
  scrollcontainer: {
    paddingHorizontal: 15,
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
  },
  recentsearchbox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  recentsearchtxt: {
    fontSize: 16,
    fontFamily: Fonts.Assistant400,
    color: '#4A4A4A',
  },
  cleartxt: {
    color: Colors.primarycolor,
    fontSize: 14,
    fontFamily: Fonts.Assistant600,
  },
  searchlistbox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomColor: '#EDEDED',
  },
  searchlisttxt: {
    fontSize: 14,
    fontFamily: Fonts.Assistant400,
    color: '#979797',
  },
  discovertxt: {
    paddingVertical: 15,
    fontSize: 16,
    fontFamily: Fonts.Assistant400,
    color: '#4A4A4A',
  },
  chipcontainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  chipbox: {
    backgroundColor: '#F3ECE8',
    paddingVertical: 3,
    paddingHorizontal: 12,
    borderRadius: 30,
    marginRight: 10,
    marginBottom: 10,
  },
  chiptxt: {fontSize: 18, fontFamily: Fonts.Assistant400, color: '#4A4A4A'},
  trendingnowtxt: {
    paddingVertical: 20,
    fontFamily: Fonts.Assistant400,
    fontSize: 16,
    color: '#4A4A4A',
  },
  headingbox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: '#F6F6F6',
    width: '100%',
  },
  productcounttxt: {
    fontFamily: Fonts.Assistant600,
    fontSize: 12,
  },
  rightheaderbox: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '30%',
  },
  rightheadertxt: {
    fontFamily: Fonts.Assistant400,
    fontSize: 16,
    color: Colors.primarycolor,
  },
  cardcontainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    backgroundColor: '#ffffff',
    flexGrow: 1,
    paddingBottom: 20,
  },
  noresultfounttxt1: {
    fontSize: 16,
    fontFamily: Fonts.Assistant700,
    paddingVertical: 20,
    color: '#4A4A4A',
  },
  noresultfounttxt2: {
    fontSize: 14,
    fontFamily: Fonts.Assistant400,
    lineHeight: 19,
    color: '#4A4A4A',
  },
});
